export const EGYPT_GOVERNORATES = [
  { value: 'cairo',        label: 'القاهرة'        },
  { value: 'giza',         label: 'الجيزة'         },
  { value: 'alexandria',   label: 'الإسكندرية'     },
  { value: 'sharkia',      label: 'الشرقية'        },
  { value: 'gharbia',      label: 'الغربية'        },
  { value: 'menofia',      label: 'المنوفية'       },
  { value: 'dakahlia',     label: 'الدقهلية'       },
  { value: 'ismailia',     label: 'الإسماعيلية'    },
  { value: 'portsaid',     label: 'بورسعيد'        },
  { value: 'suez',         label: 'السويس'         },
  { value: 'beheira',      label: 'البحيرة'        },
  { value: 'kafrelshiekh', label: 'كفر الشيخ'      },
  { value: 'damietta',     label: 'دمياط'          },
  { value: 'minya',        label: 'المنيا'         },
  { value: 'assiut',       label: 'أسيوط'          },
  { value: 'sohag',        label: 'سوهاج'          },
  { value: 'qena',         label: 'قنا'            },
  { value: 'luxor',        label: 'الأقصر'         },
  { value: 'aswan',        label: 'أسوان'          },
  { value: 'redsea',       label: 'البحر الأحمر'   },
  { value: 'southsinai',   label: 'جنوب سيناء'     },
  { value: 'northsinai',   label: 'شمال سيناء'     },
  { value: 'matrouh',      label: 'مطروح'          },
  { value: 'newvalley',    label: 'الوادي الجديد'  },
  { value: 'fayoum',       label: 'الفيوم'         },
  { value: 'benisuef',     label: 'بني سويف'       },
]

export const UNITS_BY_GOVERNORATE = {
  cairo:        ['وحدة القاهرة المركزية', 'وحدة مدينة نصر', 'وحدة شبرا', 'وحدة حلوان', 'وحدة المعادي'],
  giza:         ['وحدة الجيزة المركزية', 'وحدة 6 أكتوبر', 'وحدة الشيخ زايد', 'وحدة الهرم'],
  alexandria:   ['وحدة الإسكندرية المركزية', 'وحدة العجمي', 'وحدة برج العرب', 'وحدة المنتزه'],
  sharkia:      ['وحدة الزقازيق', 'وحدة بلبيس', 'وحدة العاشر من رمضان'],
  gharbia:      ['وحدة طنطا', 'وحدة المحلة الكبرى', 'وحدة كفر الزيات'],
  menofia:      ['وحدة شبين الكوم', 'وحدة منوف', 'وحدة السادات'],
  dakahlia:     ['وحدة المنصورة', 'وحدة ميت غمر', 'وحدة طلخا'],
  ismailia:     ['وحدة الإسماعيلية المركزية', 'وحدة القنطرة', 'وحدة أبو صوير'],
  portsaid:     ['وحدة بورسعيد المركزية', 'وحدة بورفؤاد'],
  suez:         ['وحدة السويس المركزية', 'وحدة الأربعين', 'وحدة عتاقة'],
  beheira:      ['وحدة دمنهور', 'وحدة كفر الدوار', 'وحدة إيتاي البارود'],
  kafrelshiekh: ['وحدة كفر الشيخ المركزية', 'وحدة بيلا', 'وحدة دسوق'],
  damietta:     ['وحدة دمياط المركزية', 'وحدة رأس البر', 'وحدة فارسكور'],
  minya:        ['وحدة المنيا المركزية', 'وحدة ملوي', 'وحدة بني مزار'],
  assiut:       ['وحدة أسيوط المركزية', 'وحدة ديروط', 'وحدة أبنوب'],
  sohag:        ['وحدة سوهاج المركزية', 'وحدة أخميم', 'وحدة طهطا'],
  qena:         ['وحدة قنا المركزية', 'وحدة نجع حمادي', 'وحدة قوص'],
  luxor:        ['وحدة الأقصر المركزية', 'وحدة الأقصر الغربية'],
  aswan:        ['وحدة أسوان المركزية', 'وحدة كوم أمبو', 'وحدة أبو سمبل'],
  redsea:       ['وحدة الغردقة', 'وحدة سفاجا', 'وحدة شرم الشيخ الإدارية'],
  southsinai:   ['وحدة الطور', 'وحدة دهب', 'وحدة شرم الشيخ'],
  northsinai:   ['وحدة العريش', 'وحدة رفح', 'وحدة الشيخ زويد'],
  matrouh:      ['وحدة مرسى مطروح', 'وحدة سيوة', 'وحدة الضبعة'],
  newvalley:    ['وحدة الخارجة', 'وحدة الداخلة', 'وحدة الفرافرة'],
  fayoum:       ['وحدة الفيوم المركزية', 'وحدة إطسا', 'وحدة طامية'],
  benisuef:     ['وحدة بني سويف المركزية', 'وحدة الواسطى', 'وحدة ناصر'],
}

export function getUnits(governorate) {
  if (!governorate) return []
  return (UNITS_BY_GOVERNORATE[governorate] || []).map(u => ({ value: u, label: u }))
}
