export const MOCK_PATIENT = {
  id: 1,
  name: 'فاطمة أحمد محمود',
  english_name: 'Fatima Ahmed Mahmoud',
  mrn: 'F001234',
  mfn: 'MFN-2021-0089',
  age: 32,
  date_of_birth: '1992-06-14',
  gender: 'Female',
  mobile: '01012345678',
  email: 'fatima.ahmed@email.com',
  current_address: '15 شارع النيل، المعادي، القاهرة',
  city: 'Cairo',
  patient_type: 'Normal',
  is_foreign: false,
  is_single: false,
  is_baby_patient: false,
  id_no: '29206140100123',
  passport: '',
  insurance_company: 'GlobeMed Egypt',
  insurance_plan: 'Gold Plan',
  couple_id: 'محمد علي سالم',
  diagnostic: '<p>PCOS — Polycystic Ovary Syndrome confirmed via ultrasound (2023-03-10).</p>',
  Drug_Allergies: '<p>Penicillin — severe reaction documented (2020).</p>',
  general_notes: '<p>Patient prefers morning appointments. Husband attends most visits.</p>',
  count_outpatient: 8,
  count_emergency: 2,
  count_lab: 12,
  count_radiology: 5,
};

export const MOCK_VISITS = [
  {
    id: 101, type: 'عيادات خارجية',
    date: '2024-11-20T09:30:00',
    clinic: 'عيادة الباطنة',
    doctor: 'د. حسام الدين',
    decision: 'كشف',
    state: 'Done',
  },
  {
    id: 102, type: 'طوارئ',
    date: '2024-10-05T11:00:00',
    clinic: 'غرفة الطوارئ',
    doctor: 'د. سارة خليل',
    decision: '',
    state: 'Confirmed',
  },
  {
    id: 103, type: 'تحاليل',
    date: '2024-08-18T10:15:00',
    clinic: 'معمل التحاليل',
    doctor: 'د. حسام الدين',
    decision: 'صورة دم كاملة',
    state: 'Done',
  },
  {
    id: 104, type: 'أشعة',
    date: '2024-06-01T08:00:00',
    clinic: 'قسم الأشعة',
    doctor: 'د. رانيا مصطفى',
    decision: 'أشعة مقطعية',
    state: 'Done',
  },
  {
    id: 105, type: 'عيادات خارجية',
    date: '2024-04-22T09:00:00',
    clinic: 'عيادة القلب',
    doctor: 'د. حسام الدين',
    decision: 'استشارة',
    state: 'Done',
  },
  {
    id: 106, type: 'عيادات خارجية',
    date: '2024-02-10T13:30:00',
    clinic: 'عيادة العظام',
    doctor: 'د. سارة خليل',
    decision: 'متابعة',
    state: 'Arrived',
  },
  {
    id: 107, type: 'طوارئ',
    date: '2023-12-05T10:00:00',
    clinic: 'غرفة الطوارئ',
    doctor: 'د. حسام الدين',
    decision: '',
    state: 'Done',
  },
];

export const MOCK_PATIENTS_LIST = [
  { id: 1, name: 'فاطمة أحمد محمود',   english_name: 'Fatima Ahmed Mahmoud',   mrn: 'F001234', mobile: '01012345678', age: '٣٢', gender: 'أنثى', status: ['حرج'],   diagnosis: ['أمراض القلب'],              ward: 'العناية',  date: '١٦/٠٣/٢٠٢٦' },
  { id: 2, name: 'محمد علي سالم',       english_name: 'Mohamed Ali Salem',       mrn: 'M001235', mobile: '01098765432', age: '٢٨', gender: 'ذكر',   status: ['انتهى العلاج'],  diagnosis: ['كسر في الساق'],             ward: 'العظام',   date: '١٤/٠٣/٢٠٢٦' },
  { id: 3, name: 'نورهان يوسف',         english_name: 'Nourhan Youssef',         mrn: 'F001236', mobile: '01123456789', age: '٤٠', gender: 'أنثى', status: ['بدأ العلاج'], diagnosis: ['التهاب رئوي'],              ward: 'الصدرية',  date: '١٧/٠٣/٢٠٢٦' },
  { id: 4, name: 'أحمد حسن إبراهيم',   english_name: 'Ahmed Hassan Ibrahim',    mrn: 'M001237', mobile: '01234567890', age: '٤٥', gender: 'ذكر',   status: ['بدأ العلاج'], diagnosis: ['ضغط الدم', 'سكري'],        ward: 'الباطنة',  date: '١٥/٠٣/٢٠٢٦' },
  { id: 5, name: 'خالد ناصر العتيبي',  english_name: 'Khaled Nasser Al-Otaibi', mrn: 'M001238', mobile: '01112345678', age: '٦٠', gender: 'ذكر',   status: ['بدأ العلاج'], diagnosis: ['فشل كلوي', 'سكري'],        ward: 'الكلى',    date: '١٢/٠٣/٢٠٢٦' },
  { id: 6, name: 'نورة يوسف القحطاني', english_name: 'Noura Youssef Al-Qahtani',mrn: 'F001239', mobile: '01156789012', age: '٤٠', gender: 'أنثى', status: ['انتهى العلاج'],  diagnosis: ['عملية زائدة دودية'],       ward: 'الجراحة',  date: '١٣/٠٣/٢٠٢٦' },
  { id: 7, name: 'عبدالله مصطفى حسن',  english_name: 'Abdullah Mustafa Hassan', mrn: 'M001240', mobile: '01187654321', age: '١٨', gender: 'ذكر',   status: ['حرج'],   diagnosis: ['حادث مروري', 'نزيف داخلي'], ward: 'العناية', date: '١٨/٠٣/٢٠٢٦' },
];
